version: "3.1"

services:

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 3

  alloy:
    image: grafana/alloy:v1.13.0
    container_name: grafana-alloy
    env_file:
      - .env
    volumes:
      - ./docker-config/alloy/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy
    ports:
      - "4317:4317"   # OTEL gRPC
      - "4318:4318"   # OTEL HTTP
      - "9999:9999"   # Pyroscope HTTP
      - "12345:12345" # Alloy HTTP
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy
      - --server.http.listen-addr=0.0.0.0:12345
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:12345/-/healthy" ]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  postgres_data:
  alloy_data: